# Generated by Django 5.0.2 on 2024-02-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollnumber', models.IntegerField()),
                ('department', models.CharField()),
                ('year', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
