# Generated by Django 5.0.2 on 2024-03-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_message_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
