# Generated by Django 5.0.2 on 2024-03-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_alter_message_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Me',
        ),
    ]
